[config]

[templates.fluxer]
input_path = '~/.config/matugen/templates/fluxer.css'
output_path = '~/.config/matugen/theme_output/fluxer_matugen.css'

[templates.aqueous_settings]
input_path = '/usr/share/aqueous/settings-application/themes/dms.json.in'
output_path = '~/.cache/aqueous/settings-application/themes/dms.json'

[templates.equibop]
input_path = '~/.config/matugen/templates/discord-midnight.css'
output_path = '~/.config/equibop/themes/midnight.css'

[templates.steam]
input_path = '~/.config/matugen/templates/steam.css'
output_path = '~/.config/AdwSteamGtk/custom.css'
post_hook = 'adwaita-steam-gtk -i'
